### ISSUE TITLE
Realistic word search

### ISSUE THREAD

**Issue by mvahowe** [Proskomma/perfidy#22]
There's a really basic implementation of word search in the existing transforms. This could be extended to the point where the editor could use it. Possible improvements include

- [x] Search for any string, or for one or more words in any order
- [ ] Search by verse or by paragraph
- [x] Case-sensitive/insensitive search
- [x] Regex search

This would probably be much easier if the PERF were first simplified. See  `simplifyPerfPipeline.json` for how to do this for a search within a verse. (It would still be necessary to handle verses split over several paragraphs, as in Psalms.) For search by paragraph it might make sense to first strip out chapter and verse numbers.

**Comment by superdav42** [comment]
We have a few questions:
What should the output format be. Currently it's just a list of chapter and verses that included the matching word. 1:3,5:1 etc. Is this enough or do we need to specify which element is matched so it can be highlighted.

Do we make a different transform for each different search type? It seems a bit much but I don't see an easy way to add several parameters to a transform to toggle Case sensitivity or regex etc.

Perhaps would help the most to know the use case we are targeting for this search?

**Comment by mvahowe** [comment]
@superdav42 I think we did most of this in our conversation. Re use case, I think we're aiming for "good enough to be useful" search in the editor. Proskomma does a lot more, but there's definitely a use case for the basics with as few dependencies as possible and, especially, NOW.

**Comment by PhotoNomad0** [comment]
@superdav42 I wonder if we can just handle the first three search options in the same search transform.  Maybe have 3 binary parameters defaulting to zero if not specified:
1. matchMultipleWords
2. caseSensitive
3. searchByParagraph

Maybe we could add a regex parameter to the same search transform, but if it is enabled then options 1 & 2 are ignored.

**Comment by PhotoNomad0** [comment]
@superdav42 shall we do test driven development?

**Comment by PhotoNomad0** [comment]
@superdav42 It looks like you have accomplished a lot in your unittest branch!

**Comment by PhotoNomad0** [comment]
Suggestion from Mark Howe:
```
This content will be returned via an API via a "search" method. So maybe we want something like this?
{
  bookCode: "TIT",
  searchTerms: ["Mary", "Joseph"],
  options: ["andLogic", "ignoreCase", "matchWholeWord"]
  matches: [
    {
      chapter: "3",
      verses: "16",
      content: [
        "They went quickly and found ",
        {
          type: "wrapper",
          subtype: "x-search-match",
          content: [
            "Mary"
          ]
        },
        " and ",
        {
          type: "wrapper",
          subtype: "x-search-match",
          content: [
            "Joseph"
          ]
        },
        ", and the baby lying in the manger."
      ]
    }
  ]
}
```

**Comment by superdav42** [comment]
It sounds like we should keep the content as is so using simplifyPerfPipeline.json won't really work if we don't want to modify the content. Can we still use simplifyPerfPipeline.json?
